name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: itd2-website
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Copy files to GCS
      run: gsutil -m cp -r * gs://www.itd2.net
